import type { UserBusinessInput, Slide, VCPersona, VCCritiqueResult, SlideRevisionDiff } from '../types/pitch';
import type { ResearchDossier } from '../agents/researchAgent';

export const GEMINI_API_KEY_STORAGE_KEY = 'pitcharchitect_gemini_api_key';

export function getStoredGeminiApiKey(): string {
  try {
    return localStorage.getItem(GEMINI_API_KEY_STORAGE_KEY) || (import.meta.env.VITE_GEMINI_API_KEY as string) || '';
  } catch {
    return '';
  }
}

export function setStoredGeminiApiKey(key: string): void {
  try {
    if (key.trim()) {
      localStorage.setItem(GEMINI_API_KEY_STORAGE_KEY, key.trim());
    } else {
      localStorage.removeItem(GEMINI_API_KEY_STORAGE_KEY);
    }
  } catch {}
}

export async function generateDynamicDeckWithGemini(
  input: UserBusinessInput,
  apiKey: string,
  persona: VCPersona
): Promise<{
  slides: Slide[];
  researchDossier: ResearchDossier;
  initialCritique: VCCritiqueResult;
  finalCritique: VCCritiqueResult;
  revisionDiffs: SlideRevisionDiff[];
}> {
  const prompt = `
You are an institutional venture partner and master pitch deck architect.
Synthesize a complete, fundable 10-slide startup pitch blueprint specifically for the following concept:

Company / Idea: "${input.businessIdea}"
Target Audience: "${input.targetAudience}"
Industry Vertical: "${input.industryVertical}"
Funding Stage: "${input.fundingStage}"
Revenue Model: "${input.revenueModel}"
Core Moat / Secret Sauce: "${input.uspOrMoat || 'Proprietary intelligence & high switching costs'}"
Selected Reference Archetype: "${input.selectedReferenceArchetype || 'sequoia-blueprint'}"
Target VC Persona: "${persona}"

Instructions:
1. Do NOT use generic placeholder text or dummy names. Generate realistic domain-specific pain points, metrics, pricing, competitors, team pedigrees, and bottom-up market arithmetic.
2. Return ONLY a valid, parseable JSON object matching this exact structure:
{
  "researchDossier": {
    "vertical": string,
    "industryCagr": string,
    "tamFigure": string,
    "samFigure": string,
    "somFigure": string,
    "bottomUpMath": {
      "targetUnits": number,
      "targetUnitsLabel": string,
      "arpuAnnual": number,
      "arpuFormatted": string,
      "calculatedSom": string,
      "stepExplanation": string
    },
    "unitEconomicsBenchmark": {
      "benchmarkCac": string,
      "benchmarkLtv": string,
      "ltvCacRatio": string,
      "typicalPaybackMonths": string,
      "grossMarginPercent": string
    },
    "competitorComps": [
      { "name": string, "marketShare": string, "weakness": string, "differentiatorVsUs": string }
    ],
    "groundedFootnotes": [
      {
        "id": string,
        "claim": string,
        "sourceType": "grounded_comp" | "formula_derived" | "reference_archetype" | "founder_estimate",
        "sourceLabel": string,
        "formulaOrCitation": string,
        "confidenceScore": number,
        "confidenceTier": string
      }
    ]
  },
  "slides": [
    // Array of 10 slide objects matching Slide interface for:
    // 1. problem, 2. solution, 3. market_size, 4. business_model, 5. competition, 6. go_to_market, 7. team, 8. financials, 9. traction, 10. funding_ask
  ],
  "initialScore": number,
  "finalScore": number,
  "criticalRedFlags": string[],
  "partnerObjections": [
    { "question": string, "objectionContext": string, "suggestedRemedy": string }
  ]
}
`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.4,
          responseMimeType: 'application/json'
        }
      })
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API returned status ${response.status}: ${await response.text()}`);
  }

  const data = await response.json();
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!rawText) {
    throw new Error('No text generated by Gemini model');
  }

  const parsed = JSON.parse(rawText);
  return parsed;
}
